# User config
author: "Brian Kopleck"
description: "TODO this"
keywords: "Game Design, Narrative Design, System Design, Scripting"
email: "brian@kopleck.com"
linkedin: "https://www.linkedin.com/in/bkopleck/"
twitter: "https://twitter.com/bkopleck"
github: "https://github.com/bkopleck"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed